version: '3.8'

services:
  api:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/api_dev        
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/api_test  
    depends_on:   
      - api-db

  api-db:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres